# Site settings
title: Illinois Institute of Technology
course_name: Chem 456 - Computational Biochemistry and Drug Design
course_description: "A project-based introduction to computer-aided drug design tools and the principles behind them. Structural alignment and homology modeling. Molecular docking and molecular mechanics force fields for binding enthalpies. Continuum dielectric models of electrostatics and solvation. The Boltzmann distribution and alchemical binding free energy calculations. Quantitative structure property relationships. Business, legal, and ethical considerations of drug development."
course_semester: "Spring 2026"
description: |
    Instructor: David Minh

baseurl: "/Chem456-2026S" # the subpath of your site, e.g. /blog
url: "http://daveminh.github.io/" # the base hostname & protocol for your site
githubdir: "daveminh/Chem456-2026S"

# Author/user information
email: david.minh@iit.edu
# twitter_username: username
github_username:  daveminh
authorurl: "http://mypages.iit.edu/~dminh"
address: |
    Department of Chemistry
    Illinois Institute of Technology
    Chicago IL, 60616
    USA

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include:
  - _images
  - _css
  - index.md
exclude: ['develop']

future: true
collections:
    events:
        output: false
    lectures:
        output: false
    assignments:
        output: false
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"

relative_links:
  enabled: true
  collections: true
